---
# Connection settings
ansible_connection: local # for local testing only

# Automation user that Ansible will create and manage
automation_user: ansible

# SSH key settings 
ansible_ssh_private_key_file: "{{ lookup('env', 'ANSIBLE_SSH_KEY') | default('~/.ssh/id_ed25519') }}"
automation_user_ssh_public_key: "{{ lookup('env', 'ANSIBLE_PUB_KEY') | default('~/.ssh/id_ed25519.pub') }}"

